### ISSUE TITLE
Willing to release the Snap name?

### ISSUE THREAD

**Issue by FelicianoTech** [bac/hub-snap#1]
Hi,

It looks like this repo is dead. This project is using the snap name of `hub` in the Snap store. I am making my own Hub snap is since this name is used, I'll have to use a different name, and then manually request an alias for the Snapcraft Team, which is a bit of work.

Any chance you'd be willing to give the name to me?

**Comment by bac** [comment]
More than happy to release the name. How’s that done?

**Comment by FelicianoTech** [comment]
Thank you I appreciate it. I've never done it before but some research in the Snapcraft Forum suggest that I needed to open up a request on the forum. I've done so here: https://forum.snapcraft.io/t/transfer-hub-snap-to-me/7308

**Comment by bac** [comment]
I have left a message on that thread. Happy to do whatever is required to get the ownership transferred to you.

Have a good weekend.

—Brad

**Comment by FelicianoTech** [comment]
It was transferred. Working on approval for publishing. Thank you.
